baseURL = "https://waberna.ch/"
languageCode = "de-ch"
title = "Coiffeur Waberna"


ignoreLogs = ["warning-goldmark-raw-html"]
[params]
logo = "images/logo.svg"
description = "Coiffeur Waberna – Ihr Coiffeur in Wabern. Ehemals Coiffeur Tscharner."
booking_url = "https://salonkee.ch/salon/coiffeur-waberna/widget/service?lang=de"
booking_label = "Jetzt Buchen"
phone = "031 961 29 86"
address = "Dorfstrasse 2, 3084 Wabern"
hero_background_image = "images/hero.jpg"
placeholder_image = "images/placeholder.jpg"
author = "Luca Fondo"

[taxonomies]
category = "categories"
service_category = "service_categories"

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10

[[menu.main]]
name = "Dienstleistungen"
pageRef = "/services"
weight = 20

[[menu.main]]
name = "Über Uns"
pageRef = "/about"
weight = 30

# [[menu.main]]
# name = "Galerie"
# pageRef = "/gallery"
# weight = 40

[[menu.main]]
name = "Blog"
pageRef = "/blog"
weight = 50

[[menu.social]]
name = "Instagram"
url = "https://www.instagram.com/coiffeur_waberna"
weight = 10
[menu.social.params]
icon = "icons/instagram.svg"

[build]
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/notwatching/hugo_stats\.json'
target = 'css'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'

[module]
[module.hugoVersion]
extended = true
min = '0.146.0'
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
disableWatch = true
source = 'hugo_stats.json'
target = 'assets/notwatching/hugo_stats.json'

[caches]
[caches.images]
dir = ':cacheDir/images'
